### ISSUE TITLE
Open/Lock Status

### ISSUE THREAD

**Issue by lollozzo** [AdamStrojek/libetrv#13]
Hello Adam, 
thank for the great work!

I'd like to support you developing this lib, if you need, my focus is to sync danfoss eco data with MQTT for home assistant (and remot control / monitor status).

Just a couple of questions:
Where did you find data map / data structure? 
Should be possible to read valve status? Open / Lock / Partial open etc?

Now i can get secret key and read data correctly (thanks to your last update) and i have a full map of device data and we can look for that in some Characteristic UUID, but  i don't know how to read them (format, lenght, padding, etc).

Greetings and thanks again!
I hope you can complete this lib, it's awesome!
Andrea

**Comment by AdamStrojek** [comment]
Hi Andrea,

> Where did you find data map / data structure?
The initial structure I found on the internet, most sources are listed here:
https://github.com/AdamStrojek/libetrv/issues/2
Unfortunately, it requires a lot of decoding to find information on structures
Also, it was containing only basic structures, rest need to be reversed engineered.

> Should be possible to read valve status? Open / Lock / Partial open etc?
I didn't find much information and I doubt that they are available. This TRV uses BLE and it is blocking its state when connected., so we cannot connect to it too often. Also connecting to it take a lot of time.

> Now i can get secret key and read data correctly (thanks to your last update) and i have a full map of device data and we can look for that in some Characteristic UUID, but i don't know how to read them (format, lenght, padding, etc).
Data that are already known are in `libetrv/data_struct.py` file. I have left them in CStruct format because most of devices use it on some level and I thought it would be the most accessible format. Unfortunately, rest of them you need to reverse-engineered by yourself. Some of them will stay mistery for a long time, also not every BLE handler can return useful data.

The library is mostly completed to be able to integrate it with some smart home application

**Comment by lollozzo** [comment]
Hi Adam, 
thanks for your feedback.

- DATA STRUCTURE MAP: ok, i'll try to do that! I'll share a full list (but you already have it, i guess) of characteristics and data, tonight. I'll check the list of unused data/handles (type, format, content, handle id,READ/WRITE, etc), not decoded yet.

- OPEN/CLOSE status: I hope to get it! You are right, we cant connect often and fast, but i hope valve status data is available, should be usefull to create a boost mode or just monitor/set status.
I attach a screenshot of my WIP on home assistant, i did a python script - every 30 mins - connecting to ecos, one by one. It collects temp, target temp, battery status and send to home assistant mqtt. **Battery usage is good, connecting 24 times in a day.**

![mqtt_eco](https://user-images.githubusercontent.com/45953926/71072068-0a434c80-217e-11ea-86a4-6c41317eb575.jpg)

My next steps in todolist:
- valve status (real time status - OPEN/CLOSE manually 0% - 100%)
- switch manual / auto mode (and setpoint temp you already managed)

I'll be in touch tonight, greetings!
Andrea

**Comment by lollozzo** [comment]
------------------------------------------------------
------------------------------------------------------
USED DATA  - Already in map
------------------------------------------------------
------------------------------------------------------

-- Characteristic <10020003-2749-0001-0000-00805f9b042f>:
ACTION: READ WRITE
HANDLE: 42
MAP: 0x2a - SETTINGS
-----------------------------
READ VALUE
-----------------------------
VALUE:b'\xbc\x96\xbf\x16\xb6\xda\xd2\xc5{\x9enPd\xcb\xdb\xfa'
VALUE TYPE:<class 'bytes'>
HANDLE TYPE:<class 'int'>
-----------------------------
READ RAW DATA:
188 150 191 22 182 218 210 197 123 158 110 80 100 203 219 250


-- Characteristic <10020005-2749-0001-0000-00805f9b042f>:
ACTION: READ WRITE
HANDLE: 45
MAP: 0x2a - TEMPERATURE
-----------------------------
READ VALUE
-----------------------------
VALUE:b'\xeb\x12\x9ao\x02\x93\x96~'
VALUE TYPE:<class 'bytes'>
HANDLE TYPE:<class 'int'>
-----------------------------
READ RAW DATA:
235 18 154 111 2 147 150 126


-- Characteristic <10020006-2749-0001-0000-00805f9b042f>:
ACTION: READ WRITE
HANDLE: 48
MAP: 0x30 - NAME
-----------------------------
READ VALUE
-----------------------------
VALUE:b'\xac\xb6\x8b,\xed M\xb5\xe0\x15\x82\x837\xac\x91\xd5'
VALUE TYPE:<class 'bytes'>
HANDLE TYPE:<class 'int'>
-----------------------------
READ RAW DATA:
172 182 139 44 237 32 77 181 224 21 130 131 55 172 145 213


-- Characteristic <10020008-2749-0001-0000-00805f9b042f>:
ACTION: READ WRITE
HANDLE: 54
MAP: 0x36 - DATETIME
-----------------------------
READ VALUE
-----------------------------
VALUE:b'\xf2\x90\xab\xcaFS\xf0A'
VALUE TYPE:<class 'bytes'>
HANDLE TYPE:<class 'int'>
-----------------------------
READ RAW DATA:
242 144 171 202 70 83 240 65

**Comment by lollozzo** [comment]
[map.txt](https://github.com/AdamStrojek/libetrv/files/3980393/map.txt)

I hope this might help somehow :)

**Comment by BTopbas** [comment]
I am happy to see peoples works in this project. Thanks for works.

**Comment by neuronflow** [comment]
@lollozzo 
> My next steps in todolist:
> 
> * valve status (real time status - OPEN/CLOSE manually 0% - 100%)
> * switch manual / auto mode (and setpoint temp you already managed)

Do you have an update? I am on a mission to change thermostate temperatures settings based on user presence. Also one should be able to manually change the temperature to manually overwrite my preprogrammed schedules.
