### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by boelle** [AdamStrojek/libetrv#18]
@AdamStrojek could you add a few examples on how to use the lib?

@Sylvania2 showed a program example here https://github.com/AdamStrojek/libetrv/issues/15 but i'm still not 100% sure

**Comment by AdamStrojek** [comment]
There is `cli.py` script that is demo for how to use this library, does it solve your problem? https://github.com/AdamStrojek/libetrv/blob/28a48676f15180d71feadca163859d4b2d8832c3/libetrv/cli.py

**Comment by boelle** [comment]
its almost 4 years since and i have long given up on this and now i purely use zigbee under Home assistant
