### ISSUE TITLE
Related projects that may help and conceptual ideas 

### ISSUE THREAD

**Issue by CodeFinder2** [AdamStrojek/libetrv#2]
Hi!

Cool project! I also planned to integrate the Eco into HA so I am very interested in your repo. :-)

Do you know about:
- https://github.com/olefriis/Eco2
  Especially, the "Thank you" section is helpful, as it points to a modified xxtea impl. (although in C#) and explains the required changes). It seems to work fine already with all (?) functionality we need although it's written in C#.
- https://github.com/dsltip/Danfoss-BLE
  Contains an explanation of the PIN/encryption/decryption stuff
- https://github.com/tlbdk/node-danfoss-eco-2
  Just a connection example in JavaScript but appears to use a self-implemented xxtea encryption/decryption (may provide additional insights).
- https://github.com/NdS-Research-Facilities/DanfossECO2
  Python3 implementation of the Eco thermostat, unfortunately for MacOS (only?). Writing and reading (setpoint/current) temperature seems to work already. Maybe more. (I cannot test, since I don't have a Mac.)

As another example, the EQ3 thermostat (also BLE based) already provides a [HA integration](https://www.home-assistant.io/components/eq3btsmart/). So, this Eco implementation may be inspired by that. Basically, It uses a separate library, named [python-eq3](https://github.com/rytilahti/python-eq3bt), which encapsulates the Python related functionality to communicate with the thermostat device. [This](https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/eq3btsmart) is the associated component implementation for the EQ3 climate component. It would allow us to avoid using MQTT at all and it's probably a more mature way to integrate it into HA since we then can re-use all existing UI front ends / components that HA provides for integrating "climate devices" (like the EQ3) in general. What do you think about this? ;-)

**Comment by AdamStrojek** [comment]
Thank you very much for this comment. I already had found the first 3 links, but the third one will be very helpful. At the start, I was thinking about creating only MQTT service that would allow connecting to Eco2 thermostats, but later after the initial code has grown I moved it to separate library inside of this repository. Depending on how this will change I can just rename this repository or later separate it

**Comment by CodeFinder2** [comment]
Sounds great! :-) Do you have any plans / schedules when you may come up with a "first working draft", just regarding the device interface stuff?

**Comment by AdamStrojek** [comment]
After finally getting encrypt working correctly I have implemented some initial CLI commands for libetrv. I would be happy if you would join in developing this library. For the first working draft, it can take some time. Libtrv should be developed as first and later it can be attached to other solution or create a new solution (new solutions always FTW ;) )

**Comment by CodeFinder2** [comment]
Hi Adam!

First of all, thanks and sorry for the late reply! Unfortunately, I was and I am still kinda busy at the moment But, yes, I would definitely like to join your project. Hiowever, I am not sure how much time I can spend on it and it may vary over time. If that's okay for, great! :-)

Do you have any coding / style guidelines to consider? And is there some "overview" what is currently working and what's not? And what are you working on right now and what should I consider as an entry point?
