### ISSUE TITLE
Packaging for PyPi

### ISSUE THREAD

**Issue by keton** [AdamStrojek/libetrv#20]
Just a quick question - do you plan to package libetrv for pypi.org? 
With my modifications to setup.py merged it should relatively straightformward.

I want this change because I'm developing [mqtt bridge for libetrv](https://github.com/keton/etrv2mqtt) targeting Home Assistant. I'm far enough to know that I'll be uploading it to pypi so users can simply go `pip3 install etrv2mqtt`. From my experience for regular people making virtualenv and installing depenedncies manually is too hard.

**Comment by AdamStrojek** [comment]
Version 0.4.1 has been released on PyPI
