### ISSUE TITLE
Danfoss firmware version 2.0

### ISSUE THREAD

**Issue by staal0** [AdamStrojek/libetrv#23]
Hey AdamStrojek.

Nice project - very useful.

I have one thermostat running firmware version 1.13 which is detected and I'm able to extract the secret key. My issue is that my other thermostats are running firmware version 2.0 and are not detected.

Is support for firmware 2.0 on your todo? If not I'll have to look into this myself.

Any pointers would be appreciated.

**Comment by AdamStrojek** [comment]
Hi,

I was unaware that there is a new firmware available. It would be great if you would take a look at changes. Probably in new firmware they changed only the naming scheme for eTRV so there are not directly visible in the library.

What are you doing to retrieve the key?

**Comment by staal0** [comment]
Yes. I will look into this. I have not retrieved any keys for firmware 2.0 versions - they are just not found.

**Comment by tommyNy** [comment]
Hi Adam,

How you get info about battery level? From advertising data or from characteristic when you connected to eTRV?

**Comment by simplenotezy** [comment]
I use firmware version 2.0 on all my thermostats as well. Would be cool to get it working with that

**Comment by staal0** [comment]
Hmm. I bought a new bluetooth dongle, removed and reinserted the batteries, and it now works great.

**Comment by staal0** [comment]
Okay. It's been a while since I looked at this. I have 3 units - all but one running firmware 1.13. I'm getting keys for all units, but not getting metrics from the one device running firmware 2.0. I'll have to look in the debug log to see if there is any hints.

Is there an easy way of obtaining a dump from the device for analysis?

**Comment by staal0** [comment]
I've been testing the last couple of days. It turned out that the issue was that there was not enough bluetooth rf. After moving the bluetooth antenna to a higher position, all now works great and running inside docker. With that said I can confirm that libtrv works with firmware 2.0.
