### ISSUE TITLE
Install on raspberry pi 3

### ISSUE THREAD

**Issue by directman66** [AdamStrojek/libetrv#5]
Hello, i try to install the project for use on another system, I can’t understand what I’m doing wrong
```
$ mkdir -p ~/venv/libetrv
$ python3 -m venv ~/venv/libetrv
$ source ~/venv/libetrv/bin/activate
потом 
git clone https://github.com/AdamStrojek/libetrv.git
cd libetrv
pip3 install -r requirements.txt
python3 setup.py install
```

```
 python -m libetrv
/home/pi/venv/libetrv/bin/python: No module named libetrv.__main__; 'libetrv' is a package and cannot be directly executed
```
I try to run the package, I get this error.

How to install and run this project?

**Comment by AdamStrojek** [comment]
libetrv is mostly library and wasn't designed to be able to start from a terminal. There is a very simple CLI interface that was build based on libfire library and can be accessed using `python -m libetrv.cli`. I do not plan on adding any extra CLI in the library itself.

**Comment by directman66** [comment]
Adam, thanks for your work, maybe help make your library friends with other systems that do not use python!
