### ISSUE TITLE
Changelog request

### ISSUE THREAD

**Issue by DamianPe** [AdamStrojek/libetrv#9]
Hi Adam,

Can you, please, attach some kind of change log? What is already implemented, what is still missing. Yesterday I tried to run your library using simple CLI but get stuck on pairing with thermostatic head. I assume that obtaining secret key is still under development, right? The only thing I can do is finding that device is present, connecting keeps failing. Is that an issue or not implemented yet?

Damian

**Comment by AdamStrojek** [comment]
Hi,

A changelog is a good idea, but for now, gitlog is enough. You rather mention TODO list or roadmap about missing features. For now, only missing thing is schedule.

Obtaining API key is already implemented. Please take a look at function `eTRVDevice.secret_key`. You can also start it from CLI by:

```
python -m libetrv.cli scan
python -m libetrv.cli device {device_mac} retrive_key
```

For future also please keep one thing per ticket

**Comment by DamianPe** [comment]
Please advise me if I should report found problems each as separate issue or keep them in one? I believe I found another issue with reading temperature...

**Comment by AdamStrojek** [comment]
The best is to create a separate ticket for each issue

**Comment by DamianPe** [comment]
Could you drop me an email to zabson(at)gmail.com, please? I'm not sure if trouble I have are real issues, faulty eTRV or it is just me who don't know how to use your lib...
